services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: whatsapp-chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ../chatbot-backend/data:/app/data
      - ../chatbot-frontend:/app/frontend
    env_file:
      - ../chatbot-backend/.env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/chatbot.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local